#
# Copyright (c) 2019
# Intel
#
# SPDX-License-Identifier: Apache-2.0
#
ARG BASE=golang:1.13-alpine
FROM ${BASE}

LABEL license='SPDX-License-Identifier: Apache-2.0' \
      copyright='Copyright (c) 2019: Intel'

RUN apk add --update --no-cache zeromq-dev bash

WORKDIR /go/src/github.com/edgexfoundry

COPY go.mod .

RUN go mod download