#
# Copyright (c) 2019
# Intel
#
# SPDX-License-Identifier: Apache-2.0
#
FROM nexus3.edgexfoundry.org:10004/edgex-golang-base:1.11.9-alpine-arm64

LABEL license='SPDX-License-Identifier: Apache-2.0' \
      copyright='Copyright (c) 2019: Intel'

RUN apk add --update --no-cache zeromq-dev

WORKDIR /go/src/github.com/edgexfoundry

COPY go.mod .

RUN go mod download